# Generated by Django 5.2.7 on 2025-10-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=16)),
                ('payload', models.JSONField()),
                ('prediction', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('insurance', 'Insurance'), ('diabetes', 'Diabetes')], max_length=16)),
                ('kind', models.CharField(choices=[('train', 'Train'), ('opt', 'Optimize'), ('rf', 'RFCompare')], max_length=16)),
                ('params', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
